Repository infiniteoverflow/Flutter-Tutorial-App, pull requests merged in 2021-02, with the labels that each got.

#11 Update README.md
  README.md
Labels: crossWoc, good first issue

#13 Updated-README-tagline
  README.md
Labels: crossWoc, good first issue

#10 Added config file for Welcome BOT
  .github/config.yml
Labels: crossWoc, good first issue

#14 Made the README link clickable
  README.md
Labels: crossWoc, good first issue

#15 Splash Screen Added
  assets/images/flutter_logo.png
  lib/main.dart
  lib/screens/splashScreen.dart
  pubspec.yaml
Labels: crossWoc, difficulty: easy

#18 Add Contributing Guidelines File
  CONTRIBUTING_GUIDELINES.md
Labels: crossWoc, good first issue

#19 Designed the home Screen
  lib/screens/accounts.dart
  lib/screens/homeScreen.dart
  lib/screens/splashScreen.dart
  pubspec.yaml
Labels: crossWoc, difficulty: medium

#21 Splash screen implementation
  lib/screens/splashScreen.dart
Labels: crossWoc, difficulty: easy

#25 Added Intro screen
  lib/main.dart
  lib/models/hivePreferences.dart
  lib/models/hivePreferences.g.dart
  lib/models/introScreen.dart
  lib/screens/introScreen.dart
  lib/screens/splashScreen.dart
  lib/utils/constants.dart
  pubspec.yaml
Labels: crossWoc, difficulty: medium
